app:
  - .github/filter.yaml
  - .github/workflows/app-*.yaml
  - apps/**/*
  - packages/**/*
  - .npmrc
  - biome.json
  - bun.lockb
  - package.json
  - turbo.json

catalog:
  - .github/filter.yaml
  - .github/workflows/catalog-*.yaml
  - apps/catalog/**/*
  - apps/website/**/*
  - packages/**/*
  - .npmrc
  - bun.lockb
  - package.json
  - turbo.json

db:
  - .github/filter.yaml
  - .github/workflows/db-*.yaml
  - apps/api/src/infra/drizzle/schema/**/*.ts

graphql:
  - .github/filter.yaml
  - .github/workflows/graphql-*.yaml
  - packages/api-schema/**/*
