FROM oven/bun:1.0.30

# hadolint ignore=DL3008
RUN apt-get update \
  && apt-get --no-install-recommends -y install gnupg2 ca-certificates \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists

WORKDIR /workspaces/hayabusa/

COPY ./ ./
RUN bun install --frozen-lockfile
