name: catalog deploy chromatic

on: push

env:
  DATABASE_URL: postgresql://postgres:postgres@localhost:54322/postgres
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  filter:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      catalog: ${{ steps.changes.outputs.catalog }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: check for file changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/filter.yaml

  deploy-chromatic:
    runs-on: ubuntu-latest
    needs: filter
    if: needs.filter.outputs.catalog == 'true'
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.30

      - name: get bun cache directory
        id: get-bun-cache-directory
        run: echo "STORE_PATH=$(bun pm cache)" >> $GITHUB_OUTPUT

      - name: cache bun dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.get-bun-cache-directory.outputs.STORE_PATH }}
          key: ${{ runner.os }}-bun-dependencies-${{ hashFiles('**/bun.lockb') }}
          restore-keys: ${{ runner.os }}-bun-dependencies-

      - name: install dependencies
        run: bun install --frozen-lockfile

      - name: generate all package outputs
        run: bun turbo run generate

      - name: publish storybook
        uses: chromaui/action@v11
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: apps/catalog/
          buildScriptName: build

  catalog-deploy-chromatic-check:
    runs-on: ubuntu-latest
    needs: deploy-chromatic
    if: ${{ ! failure() }}
    steps:
      - name: check
        run: echo "test is successfully executed."
